### ISSUE TITLE
upload a newer package to npmjs

### ISSUE THREAD

**Issue by sodoku** [STRML/mongoose-filter-denormalize#3]
The latest version on npm is 0.1.0 which does not include the patch to support mongoose 3.4.x

**Comment by STRML** [comment]
Done, you should see `0.2.0` on npm. Thanks.

**Comment by ericzon** [comment]
Same here, it raises this warning on installing the lib:

warning mongoose-filter-denormalize > mongoose > mongodb@1.3.19: Please upgrade to 2.2.19 or higher

Thank you
