### ISSUE TITLE
Filter does not work with mongoose 3.6.X

### ISSUE THREAD

**Issue by sodoku** [STRML/mongoose-filter-denormalize#4]
The newer mongoose versions want a string for the select

http://mongoosejs.com/docs/api.html#query_Query-select

**Comment by STRML** [comment]
Thanks for pointing this out - unfortunately I have a few projects in progress and my need for this library has ended. If you have the time to fix it, could you submit a PR? I've added a compatibility notice to the README until this is fixed.
